name: FISCO-BCOS Go-SDK GitHub Actions
on:
  push:
    # branches-ignore:
    #   - "**-1.3"
    # tags-ignore:
    #   - v1.*
    paths-ignore:
      - "Changelog.md"
      - "README.md"
  pull_request:
    # branches:
    #     - '**'
  release:
    types: [published, created, edited]

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/cache@v1
        id: cache
        with:
          path: deps/
          key: deps-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
            deps-${{ runner.os }}-${{ github.ref }}
            deps-${{ runner.os }}-
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.7
      - name: check commit
        run: bash .ci/check-commit.sh
      - name: compile
        run: bash .ci/compile_test.sh
      # - name: generate code coverage
      #   run:
